version: '3'

networks:
  etl_dock:

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: dummyDB
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etl_dock 

  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
      
    volumes:
      - .:/app 
      
    depends_on:
      - db
      
    networks:
      - etl_dock
